site_name: Deta Clojure API
theme:
  name: material
  features:
    - navigation.sections
    - navigation.path
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
